version: 2
jobs:
  build:
    docker:
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/openjdk:11-jdk

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-

      - run:
          name: Prefetch Dependencies
          command: |
            ./gradlew model

      - save_cache:
          paths:
            - ~/.gradle
            - node_modules
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run:
          name: Build
          command: |
            ./gradlew build
